language: node_js
node_js:
  - "node"

sudo: required

services:
  - docker

before_install:
  - docker build -t jawwadashraf33/dockercicdaws -f Dockerfile.dev ./

scripts:
  - docker run jawwadashraf33/dockercicdaws npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  region: "ap-southeast-2"
  app: "cicddockeraws"
  env: "Cicddockeraws-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-145522208988"
  bucket_path: "cicddockeraws"
  on:
    branch: master
