sudo: required
services:
  - docker
before_install:
  - docker build -t jawwadashraf33/dockercicdaws -f Dockerfile.dev ./
scripts:
  - docker run jawwadashraf33/dockercicdaws npm run test -- --coverage
