sudo: required
language: node_js

services:
  - docker

before_install:
  - docker build -t jawwadashraf33/ci-cddockeraws -f Dockerfile.dev ./

scripts:
  - docker run jawwadashraf33/ci-cddockeraws npm run test -- --coverage
