sudo: required

services:
  - docker

before_install:
  - docker build -t jawwadashraf33/ci-cdDockerAws -f Dockerfile.dev .

scripts:
  - docker run jawwadashraf33/ci-cdDockerAws npm run test -- --coverage
